### ISSUE TITLE
Semantic Improvement from Layer 1 plots dont ignore en-to-en

### ISSUE THREAD

**Issue by fdalvi** [boknilev/nmt-repr-analysis#10]
In the notebook, You probably just need to add something like

```python
en_source_data = data[(data.source=="en") & (data.target!="en")]
en_target_data = data[(data.source!="en") & (data.target=="en")]
```

after loading the data and use these variable.

**Comment by boknilev** [comment]
Fixed in https://github.com/boknilev/nmt-repr-analysis/commit/d61cdab984237d0259db4c37b04cf51f10fc58f7
